# Generated by Django 2.2.7 on 2019-11-06 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practiceapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superhero',
            name='first_appear',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='superhero',
            name='group_affiliation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='superhero',
            name='occupation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='superhero',
            name='place_of_birth',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='superhero',
            name='publisher',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='superhero',
            name='relatives',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
