# Generated by Django 2.2.7 on 2019-11-06 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practiceapp', '0002_auto_20191106_0419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='superhero',
            old_name='bio',
            new_name='superpowers',
        ),
    ]
