# Generated by Django 2.2.7 on 2019-11-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practiceapp', '0003_auto_20191106_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='superhero',
            name='superhero_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
